"""add attachment documents

Revision ID: 4f968d38c737
Revises: be042githubmatching
Create Date: 2026-09-02 11:51:00.639734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f968d38c737'
down_revision: Union[str, Sequence[str], None] = 'be042githubmatching'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment_documents',
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('extraction_status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['card_attachments.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_documents_attachment_id'), 'attachment_documents', ['attachment_id'], unique=False)
    op.create_index(op.f('ix_attachment_documents_card_id'), 'attachment_documents', ['card_id'], unique=False)
    op.create_index(op.f('ix_attachment_documents_id'), 'attachment_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachment_documents_id'), table_name='attachment_documents')
    op.drop_index(op.f('ix_attachment_documents_card_id'), table_name='attachment_documents')
    op.drop_index(op.f('ix_attachment_documents_attachment_id'), table_name='attachment_documents')
    op.drop_table('attachment_documents')
    # ### end Alembic commands ###
